django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls"))
]

django/mysite/polls/urls.py
from django.urls import path
from . import views
app_name = 'polls'
urlpatterns = [
    path("", views.index, name="index"),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

django/mysite/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

django/mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Question

def index(request):
    lateste_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': lateste_question_list}
    return render(request, 'polls/index.html', context)

def results(request, question_id):
    question = Question(pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote (request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except KeyError:
        return render(request, 'polls/vote.html', {'question':question , 'error_message': 'Você não fez uma escolha.'})
    else:
        selected_choice.votes +=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
# Create your views here.

django/mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Poll da HashTag</title>
</head>
<body>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li> <a href="{% url 'polls:vote' question.id %}" >{{question.question_text }}</a></li>
    {% endfor %}
    </ul>    
{% else %}
        <p> No polls are available.</p>
{% endif %}
</body>
</html>

django/mysite/polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resultado da enquete</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li> {{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}} </li>
    {% endfor %}
    </ul>
    <a href="{% url 'polls:vote' question.id %}">Votar novamente?</a> 
    <a href="{% url 'polls:index' %}">ver outra enquete?</a> 
</body>
</html>

django/mysite/polls/templates/polls/vote.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vote na enquete</title>

</head>
<body>
    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fildeset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{error_message}} </strong></p>{% endif %}
        {%for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter}}" value="{{choice.id}}">
            <label for="choice{{ forloop.counter}}">{{ choice.choice_text }} </label><br>
        {%endfor%}
    </fildeset>
    <input type="submit" value="Vote">
</body>
</html>